### ISSUE TITLE
JSX 无法引入 CSS/LESS 文件

### ISSUE THREAD

**Issue by arvinxx** [haojy/weact#3]
使用 https://github.com/haojy/weact-startup 中 08-view.flex 将
```js
WXSS`
.flex-wrp{
  margin-top: 60rpx;
  display:flex;
}
.flex-item{
  width: 200rpx;
  height: 300rpx;
  font-size: 26rpx;
}
.flex-item-V{
  margin: 0 auto;
  width: 300rpx;
  height: 200rpx;
}
```
提出为一个单独的 css/less 文件，

```css
// styles.css
.flex-wrp {
  margin-top: 60rpx;
  display: flex;
}
.flex-item {
  width: 200rpx;
  height: 300rpx;
  font-size: 26rpx;
}
.flex-item-V {
  margin: 0 auto;
  width: 300rpx;
  height: 200rpx;
}
```

在 `index.jsx` 引入
```js
//index.jsx
import { Page, WXSS } from "weact";
import "./styles.css";

export default class extends Page {
   //...
}
```

 编译报错
```
ERR] SyntaxError: /Users/arvin/Documents/Tech/WxApp/weact-startup/examples/08.view.flex/pages/styles.css: Unexpected token (1:0)

> 1 | .flex-wrp {
    | ^
  2 |   margin-top: 60rpx;
  3 |   display: flex;
  4 | } 
[ERR] 因错退出监听模式 TypeError: Cannot convert undefined or null to object
```
